#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import webapp2
import storage
import commands
class MainHandler(webapp2.RequestHandler):
    def get(self):
        self.response.write('This is an http-based chat server, you can get the client (in lua) for computercraft here: https://github.com/MudkipTheEpic/chatHTTP')
class PostHandling(webapp2.RequestHandler):
	def get(self):
		if "usr" in self.request.headers:
			usr = self.request.headers['usr']
		if "data" in self.request.headers:
			data = self.request.headers['data']
		else:
			data = ""
		if "chan" in self.request.headers:
			chan = self.request.headers['chan']
		else:
			chan = "main"
		if "cmd" in  self.request.headers:
			cmd = self.request.headers['cmd']
		else:
			cmd = None
		self.response.write("true")
		if cmd == None:
			storage.data.post(chan, data)
		else:
			ret = commands.commandHandler(storage.data).handleCommand(cmd)
			self.response.write("\n")
			self.response.write(ret)
class ReceiveHandler(webapp2.RequestHandler):
	def get(self):
		if "usr" in self.request.headers:
			usr = self.request.headers['usr']
		if "slines" in self.request.headers:
			lines = self.request.headers['slines']
		else:
			lines = 10
		if "chan" in self.request.headers:
			chan = self.request.headers['chan']
		else:
			chan = "main"
		self.response.headers['Content-Type'] = 'text/plain'
		for x in storage.data.get(chan, lines):
			self.response.write(x)
			self.response.write("\n")
app = webapp2.WSGIApplication([
    ('/', MainHandler),
    ('/post', PostHandling),
    ('/get', ReceiveHandler)
], debug=True)
